services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env

  chatbot:
    build: ./chatbot
    ports:
      - "5000:5000"
    env_file:
      - ./chatbot/.env
